site_name: Hexamind
site_description: Documentation for the Hexamind library
site_author: Hexamind
repo_url: https://github.com/HexamindOrganisation/hexamind
repo_name: Hexamind
site_url: https://hexamindorganisation.github.io/hexamind
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    primary: blue
    accent: light-blue
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - diagrams

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: UserGuide/getting_started.md
      - Installation: UserGuide/installation.md
  - API Reference:
      #- Database:
          #- Adapters:
              #- Factory : ApiReference/Database/db_adapters.md
              #- ChromaDbAdapter : ApiReference/Database/chroma_db_adapter.md
              #- ElasticSearchAdapter : ApiReference/Database/elastic_db_adapter.md
          #- Ingestion: ApiReference/Database/ingestion.md
      #- Initializer: ApiReference/Initializer/initializer.md
      #- Llm: 
          #- Adapters: 
              #- Factory: ApiReference/llm/llm_factory.md
              #- Adapters: 
                  #- ILlmClient: ApiReference/llm/illm_client.md
                  #- API models: 
                      #- MistralClientAdapter: ApiReference/llm/mistral_client.md
                      #- OpenAiClientAdapter: ApiReference/llm/openai_client.md
                  #- On Premise models: ApiReference/llm/on_premise_client.md
                  #- ChatMessageFactory: ApiReference/llm/chat_message_factory.md
          #- Llm Agent: ApiReference/llm/llm_agent.md
      - Model:
          - Document: ApiReference/Models/Models/document.md
          - Model: 
                - Element: ApiReference/Models/Models/element.md
                - Container: ApiReference/Models/Models/container.md
                - Block: ApiReference/Models/Models/block.md
          - Readers:
              - IReader: ApiReference/Models/Readers/ireader.md
              - WordReader: ApiReference/Models/Readers/word_reader.md
              - HtmlReader: ApiReference/Models/Readers/html_reader.md
              - MardownReader: ApiReference/Models/Readers/markdown_reader.md
          - Builder: ApiReference/Models/Transformer/mk_transformer.md
          - Chunk: 
              - ChunkExtractor: ApiReference/Models/Chunk/chunk_extractor.md
              - Chunk: ApiReference/Models/Chunk/chunk.md
              - Tokenizer: ApiReference/Models/Chunk/tokenizer.md
          - Summarizer:  ApiReference/Models/Summarizer/summarizer.md

      #- Retriever: ApiReference/Retriever/retriever.md
      #- Utils: 
          #- Llm: 
              #- Template: ApiReference/Utils/Llm/template.md
              #- ChatMessage: ApiReference/Utils/Llm/chat_message.md
          #- Utils:
              


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      title: Table of Contents
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HexamindOrganisation/hexamind
      name: Hexamind Organisation GitHub
  copyright:
    - text: Copyright © 2024 Hexamind

  generator: false
