name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]
  push:
    tags:
      - "v*.*.*"  # This will match tags like v0.4.1, v1.0.0, etc.

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hexamind
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Update version in __init__.py
        run: |
          sed -i "s/__version__ = .*/__version__ = \"${{ steps.get_version.outputs.VERSION }}\"/" hexamind/__init__.py
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
      
      - name: Build package
        run: python -m build
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1